### ISSUE TITLE
Open SSL Error

### ISSUE THREAD

**Issue by HarshCdot26** [wernerd/ZRTP4PJ#30]
Hello,

I am getting following error on build. I followed all the instructions as per the Readme. This issue occured while using the master branch. 

In file included from ../../zsrtp/zrtp/srtp/crypto/SrtpSymCrypto.h:29:0,
                 from ../../zsrtp/zrtp/srtp/crypto/openssl/SrtpSymCrypto.cpp:25:
../../zsrtp/zrtp/srtp/CryptoContext.h:422:26: error: field ‘hmacSha1Ctx’ has incomplete type ‘HMAC_CTX {aka hmac_ctx_st}’
         HMAC_CTX         hmacSha1Ctx;
                          ^~~~~~~~~~~

OpenSSL version on my Ubuntu PC is OpenSSL 1.1.1. I saw earlier issue posted by a user earlier. It was commented that this issue was resolved and merged to master branch. But I'm still facing this issue.

Edit: I also tried to compile with OpenSSL version 3.0 same issue occured. @wernerd Please help regarding the same.

**Comment by HarshCdot26** [comment]
This issue was resolved by replacing deprecated function calls with a compatible version of OpenSSL.
